# Generated by Django 5.1.1 on 2024-11-14 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swef24application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pending_members',
            field=models.ManyToManyField(blank=True, related_name='pending_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
